# Eon Survival Config File

# Join/Leave Message
Welcome-Message: "<blue>Welcome <player> to Eon Survival!! <player> has logged in for the first time!</blue>"
Join-Message: "<gray>[<green><bold>+</green></bold>]</gray> &b<player>"
Leave-Message: "<gray>[<red><bold>-</red></bold>]</gray> <blue><player>"

# Clock Messages
Clock-Lock: "<hover:show_text:'For more information, do /discord and join for further updates'><red>Chat is locked. Please wait while we resolve the conflict. Thank you for your patience!</red></hover>"
Clock-Unlock: "<green>Chat is unlocked. You may continue to chat normally. Thank you for your patience!</green>"

# Message Format
DM-Format: "<hover:show_text:'Click anywhere to reply'><click:copy_to_clipboard:/msg <target>><gray>[<gold><player></gold> -> <gold><target></gold>] >> </gray></hover>"

# Game-mode Messages
Survival-Message: "<blue>Survival Time!"
Creative-Message: "Creative Time!"
Spectator-Message: "Spectator Time!"

# Heal/Feed Message
Heal-Message: "Healed!"
Heal-Other: "<player> has been healed!"

Feed-Message: "You have been fed"
Feed-Other: "<target> has been fed"
Feed-Cooldown-Message: "You are on cooldown for /feed"

# Clear Inventory Message
Clear-Self-Inventory: "Your inventory has been cleared"
Target-Clear-Inventory: "Your inventory has been cleared"
Clear-Other-Inventory: "<target> inventory has been cleared"

# Discord Message
Discord-Message: "&7[&6Discord&7] >> &r&b&nhttps://discord.gg/rDBm9wE"

# Vanish Messages
Vanish-Message: "&aVanished from sight"
Unvanish-Message: "&aYou can now be seen by other players"

# Night Vision Messages
NV-Message: "Granted Night Vision"
NV-Off: "Night Vision removed"
Target-NV-Message: "<target> now has infinite night vision"

# Gamemode Check Messages
GamemodeCheck-Message: "<target> is in <gamemode>"

# Pickup Command
Pickup-Off: "<target> can no longer pickup items"
Pickup-On: "<target> can now pickup items"

# Fly Messages
Fly-On: "&7[&b&lEon Fly&r&7] &bFly On"
Fly-Off: "&7[&b&lEon Fly&r&7] &bFly Off"
Target-Fly: "Target has been toggled for flying"

# Command Spy Messages
CommandSpy-On: "<green>Command Spy On"
CommandSpy-Off: "<green>Command Spy Off"
# Leaving the Prefix here since it's useful
CommandSpy-Message: "<gray>[<gold><bold>CommandSpy</bold></gold>] <blue><player></blue>: <command>"

# Top Message
Top-Message: "&bTeleported to the Top!"

# Teleport Messages
Teleport-Message: "&bSuccessfully teleported to <player>"
Tphere-Message: "&bSuccessfully teleported <target> to your location"
Cooldown-Teleport-Message: "&7Teleporting in <seconds> seconds..."
Tpa-Player-Message: "&7Teleport request sent"
Tpa-Target-Message: "Teleport request received from <player>\n>> To accept, do /tpaccept\n>> To deny, do /tpdeny"
Teleport-Deny-Message: "Teleport request has been denied"
Teleport-Successful: "Teleport successful"
Unsafe-Tp-Target-Message: "Teleportation unsuccessful. Please try again"

Delay-Seconds: 3

No-Pending-Requests: "&7You have no pending requests to accept at this time"
Pending-Request: "&7You already have a pending request to that player"

# Back Command Messages
Death-Back-Message: "Do /back to go back to your death location"
Back-Message: "Teleporting back to your death location"

# Spawn Messages
Spawn-Message: "Teleported to spawn"

# Auto Announcement Messages
Messages:
  - 'Join the discord for free weekly giveaways and announcements! >> /discord'
  - 'Obtain ranks with in game currency to gain perks (/ranks for more info)'
  - 'McMMO has various helpful skills. Do /help and go to the McMMO area to see additional info'
  - 'Jobs are the best way to make money. Do "/jobs" to see what jobs fit your playstyle'
  - 'Make sure to read over the server rules >> /rules'
  - 'To claim giveaways, make a ticket in the discord'
  - 'To learn more about what Eon has to offer, do /help and explore the possibilities'

# Delay is in seconds
Announcement-Delay: 300

# Warp Message
Warp-Cooldown: 300
Warp-Delay: 3
Warp-Message: "&bTeleporting to <warp>"

# Revive Messages
Success-Revive-Message: "&bYou have successfully been revived"

# Other Messages
Reload-Message: "&bSuccessfully reloaded"
Target-Null: "&bThat player is offline!"