# Eon Survival Config File

# Join/Leave Message
Welcome-Message: "<blue>Welcome <player> to Eon Survival!! <player> has logged in for the first time!</blue>"
Join-Message: "<gray>[<green><bold>+</green></bold>]</gray> <blue><player>"
Leave-Message: "<gray>[<red><bold>-</red></bold>]</gray> <blue><player>"

# Chat Format
Chat-Format: "&7["

# Back Message
No-Back: "There is no location to teleport back to"
Death-Back-Message: "Do /back to go back to your death location"
Back-Message: "Teleporting back to your death location"

# Fix Messages
No-Perm-All-Fix: "You do not have permission to fix all items at once"
Fix-Cooldown: "You can /fix again in <time>"
No-Item-Fix: "No item in hand found"
Success-Fix: "Item repaired!"
Success-All-Fix: "<amount> items in inventory repaired"

# Clock Messages
Clock-Lock: "<hover:show_text:'For more information, do /discord and join for further updates'><red>Chat is locked. Please wait while we resolve the conflict. Thank you for your patience!</red></hover>"
Clock-Unlock: "<green>Chat is unlocked. You may continue to chat normally. Thank you for your patience!</green>"

# Message Format
DM-Format: "<hover:show_text:'Click anywhere to reply'><click:suggest_command:/msg <target>><gray>[<gold><player></gold> -> <gold><target></gold>] >> </gray></hover>"

# Game-mode Messages
Survival-Message: "<blue>Survival Time!"
Creative-Message: "Creative Time!"
Spectator-Message: "Spectator Time!"

# Heal/Feed Message
Heal-Message: "Healed!"
Heal-Cooldown: "You can /heal again in <time>"

Feed-Message: "You have been fed"
Feed-Cooldown-Message: "You are on cooldown for /feed"

# Clear Inventory Message
Clear-Self-Inventory: "Your inventory has been cleared"

# Clear Chat Message
Clear-Chat-Immune: "You are immune to chat clear"

# PWeather Messages
PWeather-Reset: "Reset weather to server's weather"
PWeather-Set: "Set weather to <weather>"

# Discord Message
Discord-Message: "<click:open_url:'https://discord.gg/yGmwHN9Bqj'>https://discord.gg/yGmwHN9Bqj</click>"

# Night Vision Messages
NV-Message: "Granted Night Vision"
NV-Off: "Night Vision removed"

# Gamemode Check Messages
GamemodeCheck-Message: "<green><player> is in <gamemode></green>"

# Hat Messages
Hat-On: "Stylish hat"
Hat-Full: "You already got a hat on"

# Fly Messages
Fly-On: "Fly On"
Fly-Off: "Fly Off"
Target-Fly: "Target has been toggled for flying"

# Command Spy Messages
CommandSpy-On: "<green>Command Spy On"
CommandSpy-Off: "<green>Command Spy Off"
# Leaving the Prefix here since it's useful
CommandSpy-Message: "<blue><player></blue>: <command>"

# PTime Messages
PTime-Reset: "Time reset to server cycle"
PTime-Set: "Time set to <time>"

# Rename Message
Rename-Message: "<gray>Item name changed</gray>"

# Top Message
Top-Message: "Teleported to the Top!"

# Teleport Messages
Teleport-Message: "Successfully teleported to <player>"
Tphere-Message: "Successfully teleported <target> to your location"
Cooldown-Teleport-Message: "Teleporting in <seconds> seconds..."
Tpa-Player-Message: "Teleport request sent"
Tpa-Target-Message: "Teleport request received from <player>\n>> To accept, do /tpaccept\n>> To deny, do /tpdeny"
Teleport-Deny-Message: "Teleport request has been denied"
Teleport-Successful: "Teleport successful"
Unsafe-Tp-Target-Message: "Teleportation unsuccessful. Please try again"

Delay-Seconds: 3

No-Pending-Requests: "You have no pending requests to accept at this time"
Pending-Request: "You already have a pending request to that player"

# Spawn Messages
Spawn-Message: "Teleported to spawn"

# Auto Announcement Messages
Messages:
  - 'Join the discord for free weekly giveaways and announcements! >> /discord'
  - 'Obtain ranks with in game currency to gain perks (/ranks for more info)'
  - 'McMMO has various helpful skills. Do /help and go to the McMMO area to see additional info'
  - 'Jobs are the best way to make money. Do "/jobs" to see what jobs fit your playstyle'
  - 'Make sure to read over the server rules >> /rules'
  - 'To claim giveaways, make a ticket in the discord'
  - 'To learn more about what Eon has to offer, do /help and explore the possibilities'

# Delay is in seconds
Announcement-Delay: 300

# Warp Message
Warp-Cooldown: 300
Warp-Delay: 3
Warp-Message: "&bTeleporting to <warp>"

# Revive Messages
Success-Revive-Message: "You have successfully been revived"
Revive-Failure: ""
Revive-Usage: "Usage: /revive <target>"

# Other Messages
Reload-Message: "&bSuccessfully reloaded"