name: EonCore
version: ${project.version}
main: me.squid.eoncore.EonCore
api-version: 1.17
authors: [Squid]
depend: [LuckPerms, WorldGuard]
softdepend: [AsyncWorldManager]
description: Epic description
commands:
  gmc:
    permission: eoncommands.gmc
    description: Sets gamemode to creative
  gms:
    permission: eoncommands.gms
    description: Sets gamemode to survival
  gmsp:
    permission: eoncommands.gmsp
    description: Sets gamemode to spectator
  feed:
    permission: eoncommands.feed
    description: Feed people or yourself
  heal:
    permission: eoncommands.heal
    description: Feed and heal yourself
  anvil:
    permission: eoncommands.anvil
    description: Portable anvil
  enderchest:
    permission: eoncommands.enderchest
    description: Portable ender chest
    aliases: [ec, echest]
  clearinventory:
    permission: eoncommands.clearinventory
    description: Clears the inventory
    aliases: [ci]
  burn:
    permission: eoncommands.burn
    description: Burn people lol
  extinguish:
    permission: eoncommands.extinguish
    description: Sets out the fire
  admin:
    permission: eoncommands.admin
    description: Opens the Admin GUI
  softvanish:
    permission: eoncommands.softvanish
    description: Vanish from people
  discord:
    description: Shows the server discord
  disposal:
    description: Dispose of unneccasary items
    aliases: [trash]
  nightvision:
    permission: eoncommands.nightvision
    description: Grants infinite night vision without particles
    aliases: [inv]
  f:
    permission: eoncommands.f
    description: F in the chat
    aliases: [finchat]
  gamemodecheck:
    permission: eoncommands.gamemodecheck
    description: Sends back the gamemode of a player
    aliases: [gmcheck]
  pickup:
    permission: eoncommands.pickup
    description: Sets the pickup
  invsee:
    permission: eoncommands.invsee
    description: Look into another player's inventory
  fly:
    permission: eoncommands.fly
    description: Toggles fly
  commandspy:
    permission: eoncommands.commandspy
    description: Toggle seeing people's commands
  freeze:
    permission: eoncommands.freeze
    description: Freeze players in place
  top:
    permission: eoncommands.top
    description: Teleports you to the highest block available
  rules:
    description: Displays the Rules GUI for the server
    aliases: [serverrules]
  tphere:
    permission: eoncommands.tphere
    description: Teleport other players to your location
  muted:
    permission: eoncommands.muted
    description: Shows the muted players currently on the server
  teleport:
    permission: eoncommands.teleport
    description: Teleport to a specified player
    aliases: [tp]
  spawn:
    description: Teleport to spawn
  setspawn:
    permission: eoncommands.setspawn
    description: Set the spawn for the server
  wild:
    description: Test Wild Command
  tpa:
    description: Request to teleport to a player on the server
    aliases: [tpask]
  tpaccept:
    description: Accepts an incoming teleport request
  tpdeny:
    description: Denys an incoming teleport request
  back:
    description: Teleport back to the point of death or previous teleport
  warps:
    description: Displays the different warps for the server
  workbench:
    description: Opens a workbench
    permission: eoncommands.workbench
    aliases: [wb]
  tppos:
    description: Teleport to a certain position
    permission: eoncommands.tppos
  revive:
    description: Get all of your stuff back
    permission: eoncommands.revive
  staffchat:
    description: A chat that is private amongst the staff
    permission: eoncommands.staffchat
    aliases: [sc]
  kick:
    description: Kick people lol
    permission: eoncommands.kick
  clearchat:
    description: Clears the chat for people
    permission: eoncommands.clearchat
    aliases: [cc]
  rename:
    description: Rename the item in hand
    permission: eoncommands.rename
  voteranks:
    description: Displays Voteranks GUI
    aliases: [voterank, vrank]
  hat:
    description: Put a hat on your head
    permission: eoncommands.hat
  ranks:
    description: You just bruhed your last bruh
  ptime:
    description: Set the time to your pleasing
    permission: eoncommands.ptime
  pweather:
    description: Set the weather to your pleasing
    permission: eoncommands.pweather
  help:
    description: Help menu for new players
  getpos:
    description: Get the position
    permission: eoncommands.getpos
    aliases: [coords, getposition]
  fix:
    description: Fix items with a command
    permission: eoncommands.fix
  sudo:
    description: Troll people
    permission: eoncommands.sudo
  grindstone:
    description: Portable grindstone for use
    permission: eoncommands.grindstone
  message:
    description: Message other players
    aliases: [msg, pm]
  shovel:
    description: Get a claim shovel for the claim plugin
  worldlist:
    description: Teleport to worlds
    permission: eoncommands.world
  clock:
    description: Chat lock
    permission: eoncommands.clock
  ban:
    description: Ban player
    permission: eoncommands.ban
  mute:
    description: Mute player
    permission: eoncommands.mute
  uptime:
    description: Gets the server uptime in a friendly manner
    permission: eoncommands.uptime
  findblock:
    description: Found the block
    permission: eoncommands.findblock