# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          cache: 'maven'
          distribution: 'zulu'

      - name: Build Project
        run: mvn -B package -f pom.xml
      
      - id: auth
        name: GCloud Authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTHENTICATION }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: Upload JAR to Server
        run: gcloud compute scp target/EonCore-1.0.jar mceonsurvival@main-server:~/papermc/plugins
