# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_google:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Maven Builder for Spigot Plugin
        uses: JIN-InI/Maven-Builder-for-Spigot-Plugin@1.0.0
      - name: Authenticate to Google Cloud
        uses: mathieu-bour/setup-gcloud@1.3.1
        with:
          service-account-key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project: pure-courier-329320
          configure-docker: true
      - name: Upload To Server
        run: ls ~

      
